homepage/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.home, name='home'),
        url(r'^about/$', views.about, name='about'),
        url(r'^skills/$', views.skills, name='skills'),
        url(r'^interests/$', views.interests, name='interests'),
        url(r'^contact/$', views.contact, name='contact'),
]

jadwal/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^change/(?P<change_id>[0-9]+)$', views.change, name='change'),
        url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
        url(r'^create/$', views.create, name='create'),
	url(r'^$', views.list, name='list'),
]

lab5/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^jadwal/', include('jadwal.urls', namespace='jadwal')),
    url(r'^', include('homepage.urls', namespace='homepage')),
    url(r'^admin/', admin.site.urls),
]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
	hari = models.CharField(max_length=100)
	tanggal = models.DateField()
	jam = models.TimeField()
	nama_kegiatan = models.CharField(max_length=100)
	tempat = models.CharField(max_length=100)
	kategori = models.CharField(max_length=100)

	def __str__(self):
		return "{}.{}".format(self.id, self.nama_kegiatan)

jadwal/forms.py
from django import forms

from .models import Jadwal

class JadwalForm(forms.ModelForm):
	class Meta:
		model = Jadwal
		fields = [
			'hari',
			'tanggal',
			'jam',
			'nama_kegiatan',
			'tempat',
			'kategori',
		]

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
	context = {
	"page_title": "Homepage",
	}
	return render(request, 'homepage.html', context)

def about(request):
	context = {
	"page_title": "About",
	}
	return render(request, 'aboutpage.html', context)

def skills(request):
	context = {
	"page_title": "Skills",
	}
	return render(request, 'skillspage.html', context)

def interests(request):
	context = {
	"page_title": "Interests",
	}
	return render(request, 'interestspage.html', context)

def contact(request):
	context = {
	"page_title": "Contact",
	}
	return render(request, 'contactpage.html', context)

jadwal/views.py
from django.shortcuts import render, redirect

from .models import Jadwal
from .forms import JadwalForm


def create(request):
        jadwal_form = JadwalForm(request.POST or None)
        if request.method == 'POST':
                if jadwal_form.is_valid():
                        jadwal_form.save()
                return redirect('jadwal:list')

        context = {
                "page_title": "Tambah jadwal",
                "jadwal_form": jadwal_form,
        }

        return render(request, 'create.html', context)

def delete(request, delete_id):
        Jadwal.objects.filter(id=delete_id).delete()
        return redirect('jadwal:list')

def change(request, change_id):
        jadwal_change = Jadwal.objects.get(id=change_id)
        ubah = {
                'hari' : jadwal_change.hari,
                'tanggal' : jadwal_change.tanggal,
                'jam' : jadwal_change.jam,
                'nama_kegiatan' : jadwal_change.nama_kegiatan,
                'tempat' : jadwal_change.tempat,
                'kategori' : jadwal_change.kategori,
        }
                
        jadwal_form = JadwalForm(request.POST or None, initial=ubah, instance=jadwal_change)
        if request.method == 'POST':
                if jadwal_form.is_valid():
                        jadwal_form.save()
                return redirect('jadwal:list')

        context = {
                "page_title": "Tambah jadwal",
                "jadwal_form": jadwal_form,
        }

        return render(request, 'create.html', context)

def list(request):
	semua_jadwal = Jadwal.objects.all()

	context = {
		'page_title' : 'Jadwal Kegiatan Saya',
		'semua_jadwal' : semua_jadwal,
	}

	return render(request, 'list.html', context)

homepage/templates/aboutpage.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}

		<!--About Page-->
		<h1 class="aboutpage-title" id="aboutpage"> My Profile </h1>
		<div class="row">
			<div class="column">
				<img src="{% static 'images/profile.jpg' %}" alt="Me" class="imageprofile">
			</div>

			<div class="column">
				<br><br><br>
				<p class="aboutpage-text"> I’am a computer science student. I love to explore new things, learn, then adapt it, especially in the machine learning field. In my spare time, i play chess and watch movies too. </p>
			</div>
		</div>
{% endblock contents %}

homepage/templates/base_home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>
    	{% block title %}

    	{% endblock title %}
    </title>
  </head>
  <body>


    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:skills' %}">Skills</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:interests' %}">Interests</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                </li>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'jadwal:list' %}">Jadwal</a>
                </li>
                </ul>
            </div>
        </nav>


    <div class="container">
    	{% block contents %}

    	{% endblock contents %}

    </div>

  </body>
</html>

homepage/templates/contactpage.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}

		<!--Contact Page-->
		<div class="rectangle3">
			<h4 class="center-text" id="contactpage"> Contact </h4>
			<div class="row row justify-content-center">
				<div class="col-sm-1">
					<a href="https://twitter.com/vianrac">
						<img src="{% static 'images/twitter.png' %}" alt="twitter" class="imagecontact">
					</a>
				</div>
				<div class="col-sm-1">
					<a href="mailto:ravnsy@gmail.com?">
						<img src="{% static 'images/gmail.png' %}" alt="gmail" class="imagecontact">
					</a>
				</div>
				<div class="col-sm-1">
					<a href="https://www.linkedin.com/in/ronyagusvian">
						<img src="{% static 'images/linkedin.png' %}" alt="linkedin" class="imagecontact">
					</a>
				</div>
			</div>
		<div>

{% endblock contents %}

homepage/templates/homepage.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}

		<!--Homepage-->
		<div class="rectangle1"> </div>

		<div class="center-text">
		<h1 class="homepage" id="homepage"> I'am Rony Agus Vian </h1>

		<div>
			<a href="{% url 'homepage:about' %}">
				<button type="button" class="btn btn-light">about</button>
			</a>
			<a href="{% url 'homepage:skills' %}">
				<button type="button" class="btn btn-light">skills</button>
			</a>
			<a href="{% url 'homepage:interests' %}">
				<button type="button" class="btn btn-light">interests</button>
			</a>
			<a href="{% url 'homepage:contact' %}">
				<button type="button" class="btn btn-light">contact</button>
			</a>
		</div>

		<div class="rectangle2"> </div>
		</div>
			
{% endblock contents %}

homepage/templates/interestspage.html
{% extends "base.html"%}
{% load static %}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}

		<!--Interests Page-->
		<h1 class="hobbies-title center-text" id="interestspage"> Hobbies and Interests </h1>

		<div class="container">
			<div class="row">
				<div class="col">
				<h4 class="center-text margintop10"> Chess </h4>
				<h4 class="center-text margintop10"> Movies </h4> <br>
				<h4 class="center-text margintop10"> Solving Problems </h4> 
				<h4 class="center-text margintop10"> Machine Learning </h4>
				</div>
				<div class="col marginright10">
				<p class="margintop5"> I like to play chess before i go to sleep. I think this have contribution to my own decision. I will count effect when i need to make decision to something. </p>
				<p class="margintop5"> When weekend coming, usually i give time to watch movies, especially if my favorit genre just release; about comedy and drama. Most the times, i love movies that have great music and great cinematic. </p>
				<p class="margintop5"> I love to solve many problems using algorithm. Beside of train the competencies, solving problem also benefit for understand the way of critical thinking. </p>
				<p class="margintop5"> I passionate in machine learning field. I learn and sharpen it at least one hour in a day. I think in the future, machine learning can help human being to get the much better in many aspects. </p>
				</div>
			</div>
		</div>
			
{% endblock contents %}

homepage/templates/skillspage.html
{% extends "base.html"%}
{% load static %}


{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}

		<!--Skills Page-->

		<h1 class="skills-title" id="skillspage"> Skills </h1>

		<div class="row">
			<div class="column">
				<h2 class="center-text"> Programming </h2>


				<p class="center-text">Java</p>
				<div class="progress">
				  <div class="progress-bar" role="progressbar" style="width: 85%" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
				</div>

				<p class="center-text">Python</p>
				<div class="progress">
				  <div class="progress-bar" role="progressbar" style="width: 85%" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
				</div>

				<p class="center-text">C++</p>
				<div class="progress">
				  <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
				</div>

				<p class="center-text">Matlab</p>
				<div class="progress">
				  <div class="progress-bar" role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
				</div>

				<p class="center-text">HTML</p>
				<div class="progress">
				  <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
				</div>

				<p class="center-text">CSS</p>
				<div class="progress">
				  <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
			</div>

			<div class="column">
				<h2 class="center-text">Soft Skills</h2><br><br>
				<p class="center-text">Hard worker</p><br>
				<p class="center-text">Integrity</p><br>
				<p class="center-text">Team work</p><br>
				<p class="center-text">Passionate</p><br>
				<p class="center-text">Problem solving</p>
			</div>
		</div>
			
{% endblock contents %}

jadwal/templates/create.html
{% extends "base.html"%}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}
	<form method="POST">
		{%csrf_token%}
		<table>
			{{jadwal_form.as_table}}
		</table>
		  <button type="submit" class="btn btn-primary">Buat jadwal</button>
	</form>
{% endblock contents %}

jadwal/templates/list.html
{% extends "base.html"%}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}
	<h1> {{page_title}} </h1>

	<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Hari</th>
      <th scope="col">Tanggal</th>
      <th scope="col">Jam</th>
      <th scope="col">Nama Kegiatan</th>
      <th scope="col">Tempat</th>
      <th scope="col">Kategori</th>
      <th scope="col">Hapus</th>
      <th scope="col">Ubah</th>
    </tr>
  </thead>
  <tbody>

  	{% for jadwal in semua_jadwal%}
	    <tr>
	      <th scope="row">{{forloop.counter}}</th>
	      <td>{{jadwal.hari}}</td>
		  <td>{{jadwal.tanggal}}</td>
		  <td>{{jadwal.jam}}</td>
		  <td>{{jadwal.nama_kegiatan}}</td>
		  <td>{{jadwal.tempat}}</td>
		  <td>{{jadwal.kategori}}</td>
		  <td> <a class="btn btn-danger" href="{% url 'jadwal:delete' jadwal.id%}"> Hapus </a>
	  	  <td> <a class="btn btn-secondary" href="{% url 'jadwal:change' jadwal.id%}"> Ubah </a>
	    </tr>
    {% endfor %}

  </tbody>
</table>
<a class="btn btn-primary" href="{% url 'jadwal:create' %}"> Tambah </a>

{% endblock contents %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--My CSS package-->
    <link rel="stylesheet" href="{% static 'css/lab3.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>
        {% block title %}

        {% endblock title %}
    </title>
  </head>
  <body>


    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:skills' %}">Skills</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:interests' %}">Interests</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                </li>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'jadwal:list' %}">Jadwal</a>
                </li>
                </ul>
            </div>
        </nav>


    <div class="container">
        {% block contents %}

        {% endblock contents %}

    </div>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  </body>
</html>

templates/index.html
{% extends "base.html"%}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}
	<h1> {{page_title}} </h1>
{% endblock contents %}